services:
  health:
    build: .
    # image: forgejo.snowy-vibes.ts.net/spencer/health:latest
    container_name: health
    # ports:
    #   - "3001:3001"
    volumes:
      - /mnt/NVMe/Docker/health:/data
    environment:
      - NODE_ENV=production
      - DATA_DIR=/data
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    restart: unless-stopped
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=health"
      - "docktail.service.port=3001"
      - "docktail.service.service-port=443"
